test: "applcation-dev"
mongo:
  uri: "mongodb://localhost:27017"
  dbName: "jkg"
  
spring:
  mail:
    properties:
      mail:
        smtp:
          connecttimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
          auth: true
    host: "smtp.office365.com"
    username: "jmcateer@live.com"
    password: "Kristina!1"
    port: 587
