swagger:
  version: "1.0"
  title: "Out of a Hat"
  description: "RESTful endpoints for Out of a Hat"
  email: "jmcateer@live.com"

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false